### ISSUE TITLE
Moving under getoutreach org

### ISSUE THREAD

**Issue by jaredallard** [getoutreach/localizer#39]
Hi everyone! For full transparency, I'm starting to get actual dedicated time to work on this project (it used to be only outside of work). As part of this, we're currently looking to move this under the `getoutreach` repository. Here's what that'd look like:

 * License will continue to be Apache 2.0
 * Will be available at `getoutreach/localizer`
 * Everything will stay the same, but there may be a few more regular contributors from our developer tooling team at Outreach.

Just to make sure this is done in a good light/way, I want to get sign off from all contributors thusfar. A "that's fine!" or some other aspect of affirmation is great, or, feel free to push back and we can work this out!

Contributors I want to respond:

 * @databus23 
 * @lalyos

**Comment by databus23** [comment]
Keeping the license at Apache 2.0 is the only thing that matters to me. I have no problems with moving the repo

**Comment by jaredallard** [comment]
Sorry to ping everyone here, but @lalyos do you have any opinion? 😄

**Comment by lalyos** [comment]
sure, go on. I agree license is the most important.

**Comment by jaredallard** [comment]
OK! Sorry for the delay everyone, been having to work this out internally. We're looking all good for the move, but as part of this I need to ensure everyone is comfortable with their work being attributed to a DCO. @databus23 it looks like all of your stuff already does that (thanks!).

@lalyos, however, has not. Can you certify that these commits were contributed to this project within the terms of the [DCO](https://developercertificate.org/):

* https://github.com/jaredallard/localizer/commit/405e55e317e6215512336c3d58d668c0bd358d9c
* https://github.com/jaredallard/localizer/commit/88c7f82566b64c03aea6808ac2ebbcb432e9513f

**Comment by lalyos** [comment]
Well, I probably miss something, as in my previous comment, I was trying to say that I have no objections.

**Comment by jaredallard** [comment]
Perfect. All done, thanks everyone!
